import {
  EditOutlined,
  FormOutlined,
  NumberOutlined,
  ApiOutlined,
  RightSquareOutlined,
  SelectOutlined,
  CalendarOutlined,
  UploadOutlined,
  StarOutlined,
  LinkOutlined,
  FontSizeOutlined,
  BellOutlined,
  QrcodeOutlined,
  DashOutlined,
  BorderOutlined,
  SendOutlined,
  CodeOutlined,
  ClockCircleOutlined,
  ColumnHeightOutlined,
  DownOutlined,
} from '@ant-design/icons-vue';

export const iconMap = {
  FerInput: EditOutlined,
  FerTextarea: FormOutlined,
  FerInputNumber: NumberOutlined,
  FerSwitch: ApiOutlined,
  FerCheckbox: SelectOutlined,
  FerRadio: SelectOutlined,
  FerSelect: DownOutlined,
  FerCascader: RightSquareOutlined,
  FerDatePicker: CalendarOutlined,
  FerTimePicker: ClockCircleOutlined,
  FerUploadFile: UploadOutlined,
  FerRate: StarOutlined,
  FerLink: LinkOutlined,
  FerText: FontSizeOutlined,
  FerAlert: BellOutlined,
  FerQrcode: QrcodeOutlined,
  FerDivider: DashOutlined,
  FerButton: SendOutlined,
  FerSlider: BorderOutlined,
  FerIframe: CodeOutlined,
  FerGroupTitle: ColumnHeightOutlined,
};
